---
abstract: 'Provides an interface to Maxima(full-featured CAS) as well as means to visualize and compute constructible numbers.'
author:
  - 'Stefan Petrea <randomcoder1@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Constructible
requires:
  AnyEvent: 6.02
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  Carp: 0
  GD::SVG: 0.33
  List::AllUtils: 0.02
  Moose: 2.0010
  Test::More: 0
version: 0.02
